[project]
name = "sentiment-analysis-google-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "playwright>=1.51.0",
    "pytest>=8.3.5",
]
